services:
  http-server-projeto-korp:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: http-server-projeto-korp:latest
    container_name: http-server-projeto-korp
    expose:
      - "8080"
    networks:
      - korp-net

  nginx:
    image: nginx:latest
    container_name: nginx-proxy-korp
    ports:
      - "8081:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro,z
    depends_on:
      - http-server-projeto-korp
    networks:
      - korp-net

networks:
  korp-net:
    driver: bridge
