{
 "title": "Korp",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Application Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"http-server-projeto-korp\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "MiB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Request by Endpoint",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(endpoint) (http_server_projeto_korp_requests_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[5m]) *100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests/sec",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_projeto_korp_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_projeto_korp_requests_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Allocated",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes / 1024 /1024",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}